# Background and foreground colors
background = #030309
foreground = #dce5f6

# Standard colors
palette = 0=#030309
palette = 1=#e3928b
palette = 2=#9cca8a
palette = 3=#ffa7a4
palette = 4=#75a8ff
palette = 5=#9facf1
palette = 6=#65c4ff
palette = 7=#dce5f6

# Bright colors
palette = 8=#63636a
palette = 9=#ffb1a8
palette = 10=#9bdd74
palette = 11=#ffa7a4
palette = 12=#95c9ff
palette = 13=#bdc8ff
palette = 14=#4bd1ff
palette = 15=#d7ebff
