$color = rgba(3, 3, 9, 1)
$inner_color = rgba(3, 3, 9, 0.66)
$outer_color = rgba(159, 172, 241, 1)
$font_color = rgba(220, 229, 246, 1)
$placeholder_color = rgba(220, 229, 246, 0.7)
$check_color = rgba(101, 196, 255, 1)
